### ISSUE TITLE
Launching via docker: Non-functional

### ISSUE THREAD

**Issue by MWolfR** [BlueBrain/Brayns#1199]
1. I launch docker run -ti --rm -p 8200:8200 bluebrain/brayns
2. I launch docker run -ti --rm -p 8080:8080 bluebrain/brayns-ui
3. I navigate my browser to: localhost:8080?host=localhost:8200
Result:
In Chrome: "Unable to connect to remote renderer"
In Edge: "Unable to connect to remote renderer"
In Firefox: I see the Brayns interface, but nothing works: Every dropdown menu (e.g. "rendering mode") is empty. Changing the background color results in:
>  Failed to dispatch request {client = 140019624840320, id = 'b_hl8gMC', method = set-renderer, binary = 0 bytes} to entrypoints: {code = -32601, message = 'Method 'set-renderer' not found'}.

Docker under windows with WSL2 backend.

**Comment by NadirRoGue** [comment]
Hello Michael,

the brayns-ui docker image is an abandoned user interface for an old version of Brayns (<= 1.1.0).
Since 2.0.0 on wards, brayns-ui is not compatible anymore. The only existing user interface for Brayns nowadays is Brayns Circuit Studio, (https://dev.braynscircuitstudio.kcp.bbp.epfl.ch/). You need to be on EPFL VPN to access it.

**Comment by MWolfR** [comment]
Well, the description of the bluebrain/brayns image on docker still states:
> Use it together with its web UI (https://hub.docker.com/r/bluebrain/brayns-ui) in your favourite web browser: http://localhost:8080/?host=localhost:8200
I suggest that be updated...

**Comment by MWolfR** [comment]
Ok, so I launched the docker image of Brayns on my computer.
Then navigated to https://dev.braynscircuitstudio.kcp.bbp.epfl.ch 

How do I connect that UI to my Brayns instance? I tried entering the IP address:port under "connect to existing backend". But the button remains greyed out..?

**Comment by MWolfR** [comment]
Also, the "allocate a node on BB5" is non-functional.
So, https://dev.braynscircuitstudio.kcp.bbp.epfl.ch is also not working.

**Comment by NadirRoGue** [comment]
> I suggest that be updated...

The maintainer of that image left long ago, but I will try to have it updated (if not removed to avoid any future issue).

> How do I connect that UI to my Brayns instance? I tried entering the IP address:port under "connect to existing backend". But the button remains greyed out..?

You cannot use a standalone Brayns with Brayns Circuit  Studio, since it needs other software components.  The purpose of running a standalone Brayns is to use the python API to communicate with it (If you are interested on this aspect, you can find the python API documentation on this repository README)

> Also, the "allocate a node on BB5" is non-functional.
So, https://dev.braynscircuitstudio.kcp.bbp.epfl.ch/ is also not working.

I was able to launch Brayns through Brayns Circuit Studio using the Allocate a node on BB5 button. You must be on VPN, and your browser must have BBP security certificates installed in order to access the resources (You can find a link on how to install the certificates on the front page of Brayns Circuit Studio).

**Comment by Adrien4193** [comment]
Closing this issue as it doesn't seems to be anything to fix.

Let us know if we can do anything to help.
