### ISSUE TITLE
Compatibility with Ubuntu 22 or 24

### ISSUE THREAD

**Issue by utkuoguzman** [BlueBrain/Brayns#1287]
Hi,
I have read your "Building" title, it implicitly says it is not compatible anthing above Ubuntu 20. Is this assessment true? Or can it work in one of those?
Thanks.

**Comment by Adrien4193** [comment]
Hi @utkuoguzman,

It has been tested also with Ubuntu 22.04 since the "Building" title has been written.

For untested versions, it should still work as long as you have a compatible version of GCC (currently we build with GCC 12.1.0).

You can try with other versions of Ubuntu / GCC if you cannot use a tested one and open an issue if there is any compilation issue.

Let us know if you have any other questions.

**Comment by Adrien4193** [comment]
Closing for now, feel free to reopen if needed.
